O=.o
CC=gcc
CFLAGS=-march=i586 -O2 -DPBAR -DUSE_CRC32
LFLAGS=-O -s
OBJS=main$O AFIO$O

REPAIR.EXE: $(OBJS)
	$(CC) $(LFLAGS) $(OBJS) -o REPAIR.EXE

main$O: main.c incl.h makefile.ux
afio$O: AFIO.c incl.h makefile.ux

clean:
	del *$O
	del repair.exe
